# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5f905b41cd7295e85a3d7a3836a11b1"
name = "influencer-portal"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_price_rules,write_price_rules,read_discounts,write_discounts,read_orders,write_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
